[package]
name = "rsbrowse"
version = "0.1.0"
authors = ["William R. Fraser <wfraser@codewise.org>"]
description = "an interactive browser for the contents of Rust crates"
edition = "2018"

[dependencies]
rls-analysis = "0.18.0"
rls-data = "0.19.0"
serde_json = "1.0"

[dependencies.cursive]
version = "0.16"
default-features = false
features = ["pancurses-backend"]

[dev-dependencies]
lazy_static = "1.4"
