[package]
name = "rsbrowse"
version = "0.1.1"
authors = ["William R. Fraser <wfraser@codewise.org>"]
description = "an interactive browser for the contents of Rust crates"
edition = "2018"

[dependencies]
anyhow = "1"
rustdoc-types = "0.23.0"
serde_json = "1.0"

[dependencies.cursive]
version = "0.20"
default-features = false
features = ["pancurses-backend"]

[dev-dependencies]
lazy_static = "1.4"
